on:
  push: 
    branches: main
jobs:
  build_iac:
    runs_on: ubuntu_latest
    steps:
      - name: azure-login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENTID }}
          tenant-id: ${{ vars.TENANTID }}
          subscription-id: ${{ vars.SUBSCRIPTIONID }}
